# Generated by Django 3.1.6 on 2021-02-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAnother', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='Links_Img', verbose_name='显示图片'),
        ),
    ]
