# Generated by Django 3.1.6 on 2021-02-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAnother', '0002_links_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='InStationMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('name', models.CharField(max_length=100, verbose_name='标题')),
                ('title', models.TextField(blank=True, max_length=1000, null=True, verbose_name='内容')),
            ],
            options={
                'verbose_name': '站内消息',
                'verbose_name_plural': '站内消息',
                'db_table': 'InStationMessages',
            },
        ),
    ]
