# Generated by Django 3.1.6 on 2021-02-13 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_User', '0001_initial'),
        ('Blog', '0008_remove_category_parent_category'),
        ('BlogAnother', '0003_instationmessages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('name', models.CharField(max_length=100, verbose_name='标题')),
                ('title', models.TextField(blank=True, max_length=1000, null=True, verbose_name='内容')),
                ('safe', models.BooleanField(default=False, verbose_name='状态(已读/未读)')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Blog.article', verbose_name='文章关联信息')),
                ('to_users', models.ForeignKey(blank=True, help_text='回复评论', on_delete=django.db.models.deletion.DO_NOTHING, to='BlogAnother.message', verbose_name='回复评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Blog_User.usermodels', verbose_name='用户关联信息')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'db_table': 'Message',
            },
        ),
    ]
