# Generated by Django 3.1.6 on 2021-02-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAnother', '0004_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '消息评论', 'verbose_name_plural': '消息评论'},
        ),
    ]
