# Generated by Django 3.1.6 on 2021-02-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAnother', '0006_auto_20210213_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
