# Generated by Django 3.1.6 on 2021-02-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAnother', '0007_message_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-views', '-create_time', '-update_time'], 'verbose_name': '消息评论', 'verbose_name_plural': '消息评论'},
        ),
    ]
