# Generated by Django 3.1.6 on 2021-02-22 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_User', '0001_initial'),
        ('BlogAnother', '0009_remove_message_creation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessages_Set_Get',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('name', models.CharField(max_length=100, verbose_name='标题')),
                ('title', models.TextField(blank=True, max_length=1000, null=True, verbose_name='内容')),
                ('Safe', models.CharField(choices=[('y', '已读'), ('n', '未读')], default='n', max_length=20, verbose_name='用户已读/未读状态')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog_User.usermodels', verbose_name='用户外键')),
            ],
            options={
                'verbose_name': '用户收件箱',
                'verbose_name_plural': '用户收件箱',
            },
        ),
    ]
