# Generated by Django 3.1.6 on 2021-02-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAnother', '0010_usermessages_set_get'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instationmessages',
            name='name',
            field=models.CharField(max_length=30, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='instationmessages',
            name='title',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='内容'),
        ),
    ]
