# Generated by Django 3.1.6 on 2021-02-26 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAnother', '0011_auto_20210222_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='to_users',
            field=models.ForeignKey(blank=True, help_text='回复评论', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BlogAnother.message', verbose_name='回复评论'),
        ),
    ]
