# Generated by Django 3.1.6 on 2021-02-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('user_name', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('pass_word', models.CharField(max_length=300, verbose_name='用户密码')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='电话')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='头像')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
