# Generated by Django 3.1.6 on 2021-02-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodels',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='usermodels',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='电话'),
        ),
    ]
