# Generated by Django 3.1.6 on 2021-02-12 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_User', '0003_usermodels_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodels',
            name='avatar',
        ),
    ]
