# Generated by Django 3.1.6 on 2021-02-13 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_remove_article_comment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='type',
        ),
    ]
