# Generated by Django 3.1.6 on 2021-02-13 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_remove_article_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-create_time', '-update_time', 'views'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
