# Generated by Django 3.1.6 on 2021-02-13 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
    ]
